# Generated by Django 5.1.5 on 2025-01-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('friends', models.ManyToManyField(blank=True, to='tribe.user')),
                ('tribes', models.ManyToManyField(blank=True, related_name='members', to='tribe.tribe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
