# Generated by Django 5.1.5 on 2025-02-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
